// SPDX-License-Identifier: LGPL-2.0-or-later
//
// dt_writer.rs — Generate CDE Action (.dt) files from parsed desktop entries.
//
// Produces output that matches the format generated by `CreateAction`, so
// existing CDE tooling (dticon, Application Manager) recognises the files
// without any special-casing.

use crate::desktop_entry::{self, DesktopEntry};
use crate::mime_map::MimeMap;

use std::fmt::Write as FmtWrite;
use std::io;
use std::path::{Path, PathBuf};

/// The header banner placed at the top of every generated `.dt` file.
const HEADER: &str = "\
######################################################################
#
#    Common Desktop Environment (CDE)
#
#    Action and DataType Definition File
#
#      Auto-generated by dtxdgbridge (XDG .desktop → CDE bridge)
#
#      DO NOT EDIT — this file is regenerated whenever the source
#      .desktop file changes.
#
######################################################################\n\n";

/// Generate a `.dt` file for `entry` and write it to `output_dir`.
///
/// Returns the path of the written file, or `None` if the entry is not
/// actionable.
pub fn generate(
    entry: &DesktopEntry,
    mime_map: &MimeMap,
    output_dir: &Path,
) -> io::Result<Option<PathBuf>> {
    if !entry.is_actionable() {
        return Ok(None);
    }

    let mut buf = String::with_capacity(2048);

    // Header.
    buf.push_str(HEADER);

    // Primary ACTION block.
    write_primary_action(&mut buf, entry);

    // MIME type → DATA_ATTRIBUTES / DATA_CRITERIA / Open / Print actions.
    let mut file_index = 1u32;
    for mime in &entry.mime_types {
        let extensions = mime_map.extensions(mime);
        if extensions.is_empty() {
            // No known file extensions for this MIME type — skip.
            // We could add a CONTENT-based criterion later, but PATH_PATTERN is
            // far more reliable for everyday use.
            continue;
        }

        for ext in extensions {
            write_file_association(&mut buf, entry, file_index, ext);
            file_index += 1;
        }
    }

    // Write the file atomically: write to a temp name, then rename.
    let out_path = output_dir.join(format!("{}.dt", entry.id));
    let tmp_path = output_dir.join(format!(".{}.dt.tmp", entry.id));

    std::fs::create_dir_all(output_dir)?;
    std::fs::write(&tmp_path, buf.as_bytes())?;
    std::fs::rename(&tmp_path, &out_path)?;

    log::info!("wrote {}", out_path.display());
    Ok(Some(out_path))
}

/// Remove a previously generated `.dt` file (e.g. when the `.desktop` file is
/// deleted).
pub fn remove(entry_id: &str, output_dir: &Path) -> io::Result<bool> {
    let path = output_dir.join(format!("{entry_id}.dt"));
    match std::fs::remove_file(&path) {
        Ok(()) => {
            log::info!("removed {}", path.display());
            Ok(true)
        }
        Err(e) if e.kind() == io::ErrorKind::NotFound => Ok(false),
        Err(e) => Err(e),
    }
}

// ── internal helpers ─────────────────────────────────────────────────

fn write_primary_action(buf: &mut String, entry: &DesktopEntry) {
    let exec = desktop_entry::translate_exec(&entry.exec);
    let window_type = if entry.terminal {
        "PERM_TERMINAL"
    } else {
        "NO_STDIO"
    };

    writeln!(buf, "ACTION {id}", id = entry.id).ok();
    writeln!(buf, "{{").ok();
    writeln!(buf, "     LABEL         {}", entry.name).ok();
    writeln!(buf, "     TYPE          COMMAND").ok();
    writeln!(buf, "     EXEC_STRING   {exec}").ok();
    if !entry.icon.is_empty() {
        writeln!(buf, "     ICON          {}", entry.icon).ok();
    }
    writeln!(buf, "     WINDOW_TYPE   {window_type}").ok();
    if !entry.comment.is_empty() {
        writeln!(buf, "     DESCRIPTION   {}", entry.comment).ok();
    }
    writeln!(buf, "}}").ok();
    writeln!(buf).ok();
}

fn write_file_association(buf: &mut String, entry: &DesktopEntry, index: u32, ext: &str) {
    let attr_name = format!("{}_FILE_{index}", entry.id);
    let print_action_name = format!("{attr_name}_PRINT");

    // DATA_ATTRIBUTES
    writeln!(buf, "DATA_ATTRIBUTES {attr_name}").ok();
    writeln!(buf, "{{").ok();
    writeln!(buf, "     ACTIONS       Open,Print").ok();
    if !entry.icon.is_empty() {
        writeln!(buf, "     ICON          {}", entry.icon).ok();
    }
    if !entry.comment.is_empty() {
        writeln!(buf, "     DESCRIPTION   Open .{ext} files with {}", entry.name).ok();
    }
    writeln!(buf, "}}").ok();
    writeln!(buf).ok();

    // DATA_CRITERIA
    writeln!(buf, "DATA_CRITERIA {attr_name}A").ok();
    writeln!(buf, "{{").ok();
    writeln!(buf, "     DATA_ATTRIBUTES_NAME {attr_name}").ok();
    writeln!(buf, "     MODE          !d").ok();
    writeln!(buf, "     PATH_PATTERN  *.{ext}").ok();
    writeln!(buf, "}}").ok();
    writeln!(buf).ok();

    // Open (MAP to primary action)
    writeln!(buf, "ACTION Open").ok();
    writeln!(buf, "{{").ok();
    writeln!(buf, "     ARG_TYPE      {attr_name}").ok();
    writeln!(buf, "     TYPE          MAP").ok();
    writeln!(buf, "     MAP_ACTION    {}", entry.id).ok();
    writeln!(buf, "     LABEL         Open").ok();
    writeln!(buf, "}}").ok();
    writeln!(buf).ok();

    // Print action (lpr fallback)
    writeln!(buf, "ACTION {print_action_name}").ok();
    writeln!(buf, "{{").ok();
    writeln!(buf, "     TYPE          COMMAND").ok();
    writeln!(buf, "     EXEC_STRING   lpr \"%Arg_1%\"").ok();
    writeln!(buf, "     WINDOW_TYPE   NO_STDIO").ok();
    writeln!(buf, "}}").ok();
    writeln!(buf).ok();

    writeln!(buf, "ACTION Print").ok();
    writeln!(buf, "{{").ok();
    writeln!(buf, "     ARG_TYPE      {attr_name}").ok();
    writeln!(buf, "     TYPE          MAP").ok();
    writeln!(buf, "     MAP_ACTION    {print_action_name}").ok();
    writeln!(buf, "     LABEL         Print").ok();
    writeln!(buf, "}}").ok();
    writeln!(buf).ok();
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_entry() -> DesktopEntry {
        DesktopEntry {
            name: "Firefox".into(),
            exec: "/usr/lib/firefox/firefox %u".into(),
            icon: "firefox".into(),
            comment: "Browse the web".into(),
            terminal: false,
            mime_types: vec!["text/html".into()],
            no_display: false,
            hidden: false,
            id: "firefox".into(),
        }
    }

    #[test]
    fn generates_action_block() {
        let dir = tempfile::tempdir().unwrap();
        let mime_map = MimeMap::load(); // may be empty in CI
        let result = generate(&sample_entry(), &mime_map, dir.path()).unwrap();
        assert!(result.is_some());

        let content = std::fs::read_to_string(result.unwrap()).unwrap();
        assert!(content.contains("ACTION firefox"));
        assert!(content.contains("LABEL         Firefox"));
        assert!(content.contains("WINDOW_TYPE   NO_STDIO"));
        assert!(content.contains("EXEC_STRING   /usr/lib/firefox/firefox \"%Arg_1%\""));
    }

    #[test]
    fn skips_non_actionable() {
        let mut entry = sample_entry();
        entry.hidden = true;
        let dir = tempfile::tempdir().unwrap();
        let mime_map = MimeMap::load();
        assert!(generate(&entry, &mime_map, dir.path()).unwrap().is_none());
    }

    #[test]
    fn atomic_write() {
        let dir = tempfile::tempdir().unwrap();
        let mime_map = MimeMap::load();
        let entry = sample_entry();

        // Write once.
        generate(&entry, &mime_map, dir.path()).unwrap();
        // Overwrite (should not leave temp files).
        generate(&entry, &mime_map, dir.path()).unwrap();

        let files: Vec<_> = std::fs::read_dir(dir.path())
            .unwrap()
            .filter_map(Result::ok)
            .collect();
        assert_eq!(files.len(), 1);
        assert!(files[0].file_name().to_str().unwrap().ends_with(".dt"));
    }
}
