// SPDX-License-Identifier: LGPL-2.0-or-later
//
// mime_map.rs — Map MIME types to file extensions using the shared MIME database.
//
// Parses `/usr/share/mime/globs2` (the Freedesktop Shared MIME-info database
// generated by `update-mime-database`) to build a MIME-type → Vec<extension>
// lookup table.  The daemon uses this to generate CDE `DATA_CRITERIA` entries
// with proper `PATH_PATTERN` globs.

use std::collections::HashMap;
use std::io::{self, BufRead};
use std::path::Path;
use std::sync::Arc;

/// An immutable, thread-safe MIME → extensions map.
///
/// Built once at startup and shared (via `Arc`) across the watcher and
/// translator tasks without any locking.
#[derive(Debug, Clone)]
pub struct MimeMap {
    inner: Arc<HashMap<String, Vec<String>>>,
}

impl MimeMap {
    /// Load the system glob database.  Tries the well-known paths in order:
    ///
    /// 1. `~/.local/share/mime/globs2`
    /// 2. `/usr/share/mime/globs2`
    /// 3. `/usr/local/share/mime/globs2`
    ///
    /// Returns an empty map (with a warning) if none are found.
    pub fn load() -> Self {
        let home_globs = dirs_path("globs2");
        let candidates: Vec<&Path> = [
            home_globs.as_deref(),
            Some(Path::new("/usr/share/mime/globs2")),
            Some(Path::new("/usr/local/share/mime/globs2")),
        ]
        .into_iter()
        .flatten()
        .collect();

        for path in &candidates {
            match Self::parse(path) {
                Ok(map) => {
                    log::info!("loaded {} MIME mappings from {}", map.inner.len(), path.display());
                    return map;
                }
                Err(e) if e.kind() == io::ErrorKind::NotFound => continue,
                Err(e) => {
                    log::warn!("error reading {}: {e}", path.display());
                    continue;
                }
            }
        }

        log::warn!("no globs2 file found; MIME type mapping will be empty");
        Self {
            inner: Arc::new(HashMap::new()),
        }
    }

    /// Parse a single `globs2` file.
    ///
    /// Format: `weight:mime/type:*.ext` (one per line; `#` comments).
    fn parse(path: &Path) -> io::Result<Self> {
        let file = std::fs::File::open(path)?;
        let reader = io::BufReader::new(file);
        let mut map: HashMap<String, Vec<String>> = HashMap::new();

        for line in reader.lines() {
            let line = line?;
            let trimmed = line.trim();
            if trimmed.is_empty() || trimmed.starts_with('#') {
                continue;
            }

            // weight:mime/type:glob[:flags]
            let parts: Vec<&str> = trimmed.splitn(4, ':').collect();
            if parts.len() < 3 {
                continue;
            }

            let mime = parts[1];
            let glob = parts[2];

            // We only care about simple `*.ext` globs — skip complex patterns
            // like `*.so.[0-9]*`.
            if let Some(ext) = glob.strip_prefix("*.")
                && !ext.contains('*') && !ext.contains('[') && !ext.contains('?') {
                    map.entry(mime.to_owned())
                        .or_default()
                        .push(ext.to_owned());
                }
        }

        // Deduplicate extensions per MIME type.
        for exts in map.values_mut() {
            exts.sort();
            exts.dedup();
        }

        Ok(Self {
            inner: Arc::new(map),
        })
    }

    /// Look up extensions for a MIME type.  Returns an empty slice if unknown.
    pub fn extensions(&self, mime_type: &str) -> &[String] {
        self.inner.get(mime_type).map_or(&[], Vec::as_slice)
    }
}

/// Build `~/.local/share/mime/<filename>`.
fn dirs_path(filename: &str) -> Option<std::path::PathBuf> {
    let home = std::env::var("HOME").ok()?;
    Some(
        Path::new(&home)
            .join(".local/share/mime")
            .join(filename),
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write;

    #[test]
    fn parse_globs2_sample() {
        let mut f = tempfile::NamedTempFile::new().unwrap();
        writeln!(
            f,
            "# comment\n\
             80:text/html:*.html\n\
             80:text/html:*.htm\n\
             50:application/pdf:*.pdf\n\
             50:image/png:*.png\n\
             60:application/x-sharedlib:*.so.[0-9]*"
        )
        .unwrap();

        let map = MimeMap::parse(f.path()).unwrap();
        assert_eq!(map.extensions("text/html"), &["htm", "html"]);
        assert_eq!(map.extensions("application/pdf"), &["pdf"]);
        assert_eq!(map.extensions("image/png"), &["png"]);
        // Complex glob should be filtered out.
        assert!(map.extensions("application/x-sharedlib").is_empty());
        // Unknown type.
        assert!(map.extensions("application/unknown").is_empty());
    }
}
