// Generates `include/libbil_parser.h` for C callers.
// Mirrors the cbindgen pattern used in cde/lib/DtSvc/rust/build.rs.

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let include_dir = Path::new(&crate_dir).join("include");
    fs::create_dir_all(&include_dir).unwrap();

    println!("cargo:rerun-if-changed=src");
    println!("cargo:rerun-if-changed=build.rs");

    let builder = cbindgen::Builder::new()
        .with_crate(&crate_dir)
        .with_language(cbindgen::Language::C)
        .with_include_guard("CDE_LIBBIL_PARSER_H")
        .with_autogen_warning(
            "/* DO NOT EDIT — generated by cbindgen from cde/programs/dtappbuilder/rust */",
        )
        .with_documentation(true);

    match builder.generate() {
        Ok(bindings) => {
            bindings.write_to_file(include_dir.join("libbil_parser.h"));
        }
        Err(e) => {
            println!("cargo:warning=cbindgen failed: {e}");
        }
    }
}
