// Generates `include/libdt_parser.h` so C consumers (dtaction, dtfile,
// dtwm/DataBaseLoad.c, ...) can call the Rust .dt parser through a stable
// opaque-handle API. Follows the cbindgen pattern already in use at
// `cde/lib/csa/rust/build.rs`.

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let include_dir = Path::new(&crate_dir).join("include");
    fs::create_dir_all(&include_dir).unwrap();

    println!("cargo:rerun-if-changed=src");
    println!("cargo:rerun-if-changed=grammar/dtfile.pest");
    println!("cargo:rerun-if-changed=build.rs");

    // cbindgen is best-effort during the initial migration: the Rust code
    // still builds without headers, which means developers who don't need
    // the C API (e.g. `cargo test`) don't hit an install-time dependency.
    let builder = cbindgen::Builder::new()
        .with_crate(&crate_dir)
        .with_language(cbindgen::Language::C)
        .with_include_guard("CDE_LIBDT_PARSER_H")
        .with_autogen_warning("/* DO NOT EDIT — generated by cbindgen from cde/lib/DtSvc/rust */")
        .with_documentation(true);

    match builder.generate() {
        Ok(bindings) => {
            bindings.write_to_file(include_dir.join("libdt_parser.h"));
        }
        Err(e) => {
            println!("cargo:warning=cbindgen failed: {e}");
        }
    }
}
