#ifndef CDE_LIBDT_PARSER_H
#define CDE_LIBDT_PARSER_H

/* DO NOT EDIT — generated by cbindgen from cde/lib/DtSvc/rust */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque handle returned to C. Consumers pass this back in on every call.
 */
typedef struct CdeDtHandle CdeDtHandle;

/**
 * Return the most recent error message from this thread, or NULL if the
 * previous call succeeded. The returned pointer remains valid until the
 * next FFI call on this thread.
 *
 * # Safety
 * The caller must not free the returned pointer.
 */
const char *cde_dt_last_error(void);

/**
 * Parse every `.dt` file under `path` in parallel.
 *
 * # Safety
 * `path` must point to a NUL-terminated UTF-8 string. Returns NULL on
 * failure; call [`cde_dt_last_error`] to retrieve the message.
 */
struct CdeDtHandle *cde_dt_load_dir(const char *path);

/**
 * Free a handle previously returned by [`cde_dt_load_dir`].
 *
 * # Safety
 * `handle` must be NULL or a pointer previously returned by
 * [`cde_dt_load_dir`].
 */
void cde_dt_free(struct CdeDtHandle *handle);

/**
 * Number of ACTION records loaded into the handle.
 */
uintptr_t cde_dt_action_count(const struct CdeDtHandle *handle);

/**
 * Number of DATA_ATTRIBUTES records loaded into the handle.
 */
uintptr_t cde_dt_datatype_count(const struct CdeDtHandle *handle);

/**
 * Look up an ACTION by name and return its EXEC_STRING field, or NULL if
 * the action or the field is missing. The returned pointer is owned by the
 * handle and remains valid until the handle is freed.
 *
 * # Safety
 * `handle` must be a valid pointer from [`cde_dt_load_dir`] and `name`
 * must be a NUL-terminated string.
 */
const char *cde_dt_action_get_exec(const struct CdeDtHandle *handle, const char *name);

/**
 * Look up an ACTION's LABEL field.
 *
 * # Safety
 * See [`cde_dt_action_get_exec`].
 */
const char *cde_dt_action_get_label(const struct CdeDtHandle *handle, const char *name);

/**
 * Parse a single `.dt` file into an already-existing handle. Useful for
 * reloading after a user edits a config file.
 *
 * # Safety
 * Both pointers must be valid. `file` must be NUL-terminated UTF-8.
 * Returns 0 on success, -1 on failure.
 */
int32_t cde_dt_load_file(struct CdeDtHandle *handle, const char *file);

#endif  /* CDE_LIBDT_PARSER_H */
