// Generates `include/libdtwm_parser.h` for the C callers of the dtwmrc
// parser. Follows the same cbindgen pattern as `cde/lib/csa/rust/build.rs`.

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let include_dir = Path::new(&crate_dir).join("include");
    fs::create_dir_all(&include_dir).unwrap();

    println!("cargo:rerun-if-changed=src");
    println!("cargo:rerun-if-changed=grammar/dtwmrc.pest");
    println!("cargo:rerun-if-changed=build.rs");

    let builder = cbindgen::Builder::new()
        .with_crate(&crate_dir)
        .with_language(cbindgen::Language::C)
        .with_include_guard("CDE_LIBDTWM_PARSER_H")
        .with_autogen_warning("/* DO NOT EDIT — generated by cbindgen from cde/programs/dtwm/rust */")
        .with_documentation(true);

    match builder.generate() {
        Ok(bindings) => {
            bindings.write_to_file(include_dir.join("libdtwm_parser.h"));
        }
        Err(e) => {
            println!("cargo:warning=cbindgen failed: {e}");
        }
    }
}
