#ifndef CDE_LIBDTWM_PARSER_H
#define CDE_LIBDTWM_PARSER_H

/* DO NOT EDIT — generated by cbindgen from cde/programs/dtwm/rust */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct CdeDtwmHandle CdeDtwmHandle;

/**
 * Return the most recent parse error on this thread, or NULL.
 *
 * # Safety
 * The returned pointer is owned by the thread-local; do not free it.
 */
const char *cde_dtwm_last_error(void);

/**
 * Parse a dtwmrc file from disk.
 *
 * # Safety
 * `path` must be a NUL-terminated UTF-8 string. Returns NULL on failure.
 */
struct CdeDtwmHandle *cde_dtwm_parse_file(const char *path);

/**
 * Free a handle previously returned by [`cde_dtwm_parse_file`].
 *
 * # Safety
 * `handle` must be NULL or a pointer previously returned here.
 */
void cde_dtwm_free(struct CdeDtwmHandle *handle);

/**
 * Number of top-level declarations parsed from the file.
 *
 * # Safety
 * `handle` must be valid.
 */
uintptr_t cde_dtwm_decl_count(const struct CdeDtwmHandle *handle);

/**
 * Return the declaration kind as a static string, or NULL on out-of-range.
 *
 * # Safety
 * `handle` must be valid.
 */
const char *cde_dtwm_decl_kind(const struct CdeDtwmHandle *handle, uintptr_t index);

/**
 * Return the declaration name (interned for the handle's lifetime).
 *
 * # Safety
 * `handle` must be valid.
 */
const char *cde_dtwm_decl_name(const struct CdeDtwmHandle *handle, uintptr_t index);

/**
 * Return the declaration body text (interned for the handle's lifetime).
 *
 * # Safety
 * `handle` must be valid.
 */
const char *cde_dtwm_decl_body(const struct CdeDtwmHandle *handle, uintptr_t index);

#endif  /* CDE_LIBDTWM_PARSER_H */
