// Generates `include/libcsa_recurrence.h` so the legacy CSA C callers can
// use the Rust recurrence parser through a stable opaque-handle API.
// Mirrors `cde/lib/DtSvc/rust/build.rs`.

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let include_dir = Path::new(&crate_dir).join("include");
    fs::create_dir_all(&include_dir).unwrap();

    println!("cargo:rerun-if-changed=src");
    println!("cargo:rerun-if-changed=build.rs");

    let builder = cbindgen::Builder::new()
        .with_crate(&crate_dir)
        .with_language(cbindgen::Language::C)
        .with_include_guard("CDE_LIBCSA_RECURRENCE_H")
        .with_autogen_warning("/* DO NOT EDIT — generated by cbindgen from cde/lib/csa/recurrence */")
        .with_documentation(true);

    match builder.generate() {
        Ok(bindings) => {
            bindings.write_to_file(include_dir.join("libcsa_recurrence.h"));
        }
        Err(e) => {
            println!("cargo:warning=cbindgen failed: {e}");
        }
    }
}
