#ifndef CDE_LIBCSA_RECURRENCE_H
#define CDE_LIBCSA_RECURRENCE_H

/* DO NOT EDIT — generated by cbindgen from cde/lib/csa/recurrence */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque handle returned to C.
 */
typedef struct CsaRecurrenceHandle CsaRecurrenceHandle;

/**
 * Return the most recent parse error for this thread, or NULL.
 *
 * # Safety
 * Returned pointer is owned by the thread-local; do not free.
 */
const char *csa_recurrence_last_error(void);

/**
 * Parse a recurrence rule string. Returns NULL on failure; call
 * [`csa_recurrence_last_error`] to retrieve the diagnostic.
 *
 * # Safety
 * `input` must be a NUL-terminated UTF-8 string.
 */
struct CsaRecurrenceHandle *csa_recurrence_parse(const char *input);

/**
 * Free a handle previously returned by [`csa_recurrence_parse`].
 *
 * # Safety
 * `handle` must be NULL or a pointer previously returned here.
 */
void csa_recurrence_free(struct CsaRecurrenceHandle *handle);

/**
 * Return the repeat type of the parsed rule.
 *
 * # Safety
 * `handle` must be valid.
 */
uint32_t csa_recurrence_type(const struct CsaRecurrenceHandle *handle);

/**
 * Return the interval field (every-N) of the parsed rule, or 0 on error.
 *
 * # Safety
 * `handle` must be valid.
 */
uint32_t csa_recurrence_interval(const struct CsaRecurrenceHandle *handle);

/**
 * Return the duration as a signed int: >0 = finite count, 0 = infinite,
 * -1 = not set (matches the legacy `RE_NOTSET` / `RE_INFINITY` sentinels).
 *
 * # Safety
 * `handle` must be valid.
 */
int64_t csa_recurrence_duration(const struct CsaRecurrenceHandle *handle);

#endif /* CDE_LIBCSA_RECURRENCE_H */
