#ifndef CDE_LIBBIL_PARSER_H
#define CDE_LIBBIL_PARSER_H

/* DO NOT EDIT — generated by cbindgen from cde/programs/dtappbuilder/rust */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque handle to a parsed BIL file. Allocated on the Rust heap; freed
 * by [`cde_bil_free`].
 */
typedef struct BilHandle BilHandle;

/**
 * Return the most recent parse error for this thread, or NULL if none.
 *
 * # Safety
 * The returned pointer is owned by the thread-local; do **not** free it.
 */
const char *cde_bil_last_error(void);

/**
 * Parse a BIL file given as a NUL-terminated UTF-8 string. Returns an
 * opaque handle on success, or NULL on failure — call [`cde_bil_last_error`]
 * to retrieve the diagnostic.
 *
 * # Safety
 * `input` must be a NUL-terminated UTF-8 string.
 */
struct BilHandle *cde_bil_parse(const char *input);

/**
 * Free a handle previously returned by [`cde_bil_parse`].
 *
 * # Safety
 * `handle` must be NULL or a pointer previously returned by [`cde_bil_parse`].
 */
void cde_bil_free(struct BilHandle *handle);

/**
 * Return the major version from `:bil-version`, or 0 if absent or on error.
 *
 * # Safety
 * `handle` must be valid.
 */
uint32_t cde_bil_version_major(const struct BilHandle *handle);

/**
 * Return the minor version from `:bil-version`, or 0 if absent or on error.
 *
 * # Safety
 * `handle` must be valid.
 */
uint32_t cde_bil_version_minor(const struct BilHandle *handle);

/**
 * Return the number of top-level items in the file, or 0 on error.
 *
 * # Safety
 * `handle` must be valid.
 */
uintptr_t cde_bil_item_count(const struct BilHandle *handle);

/**
 * Return the keyword of the `idx`-th top-level item as a NUL-terminated
 * interned string, or NULL if `idx` is out of range or on error.
 *
 * # Safety
 * `handle` must be valid. The returned pointer lives as long as the handle.
 */
const char *cde_bil_item_keyword(const struct BilHandle *handle, uintptr_t idx);

/**
 * Return the name (first atom arg) of the `idx`-th top-level item as a
 * NUL-terminated interned string, or NULL if none or on error.
 *
 * # Safety
 * `handle` must be valid. The returned pointer lives as long as the handle.
 */
const char *cde_bil_item_name(const struct BilHandle *handle, uintptr_t idx);

#endif  /* CDE_LIBBIL_PARSER_H */
